slides.html: slides.md
	pandoc --standalone -t slidy --css extra.css slides.md -o slides.html

slides-alond.html: slides.md
	pandoc --standalone --embed-resources -t slidy --css extra.css slides.md -o slides.html


dod-chi.html: dod-chi.md
	pandoc --standalone -t slidy --css extra.css dod-chi.md -o dod-chi.html

dod-chi-alond.html: dod-chi.md
	pandoc --standalone --embed-resources -t slidy --css extra.css dod-chi.md -o dod-chi.html


demo0:
	echo do something
