apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-runner
  namespace: flox-poc
  labels:
    app: build-runner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: build-runner
  template:
    metadata:
      labels:
        app: build-runner
    spec:
      containers:
      - name: mount-manager
        securityContext:
          privileged: true
        image: 842676004212.dkr.ecr.eu-west-3.amazonaws.com/soci-test:nix
        command: [ "/bin/sh", "-c", "--" ]
        args:
        - mkdir -p /data/upper;
          mkdir -p /data/work;
          mkdir -p /nix-overlay;

          busybox mount -t overlay -o lowerdir=/nix-ro/,upperdir=/data/upper,workdir=/data/work overlay /nix-overlay;
          
          echo doing nix stuff;
          busybox touch /nix-overlay/var/.flox-setup-finished;
 
          tail -f /dev/null;
        volumeMounts:
        - mountPath: /nix-ro
          name: host-shared-nix
          readOnly: true
        - mountPath: /data
          name: overlay
        - mountPath: /nix-overlay
          name: nix-in-container-mount
          mountPropagation: Bidirectional
        lifecycle:
          preStop:
            exec:
              command: ["umount", "/nix-overlay"]

      - image: 842676004212.dkr.ecr.eu-west-3.amazonaws.com/soci-test:nix
        name: user-build
        command: [ "/bin/sh", "-c", "--" ]
        args:
        # TODO: split mount-manager into init container and mount-cleanup
        - sleep 1; 

          nix shell
            nixpkgs#coreutils
            nixpkgs#hello
          --command echo cache hit;
          nix shell
            nixpkgs#ran
          --command echo just downloaded;
          tail -f /dev/null;
        volumeMounts:
        - mountPath: /nix
          name: nix-in-container-mount
          readOnly: false  # has write access to the overlayed nix mount
        readinessProbe:
          exec:
            command:
            - cat
            - /nix/var/.flox-setup-finished
          initialDelaySeconds: 0
          periodSeconds: 1
          failureThreshold: 300

      volumes:
      - name: host-shared-nix
        hostPath: 
          path: /hostdata/nix/
      - name: overlay
        emptyDir: {}
        #          medium: Memory
      - name: nix-in-container-mount
        emptyDir: {}
      terminationGracePeriodSeconds: 1 # TODO: workaround to kill `tail -f /dev/null`
